### ISSUE TITLE
Issue about Information-fusion

### ISSUE THREAD

**Issue by xunchang88** [MAMBA126JAMES/Information-Fusion#1]
Dear sir

  I have a question: in the code you uploaded, Does M denote multi-sensor data? What is G?

Best regards.

**Comment by JethroJames** [comment]
Thank you very much for your interest in my work! 
Yes, M represents multi-sensor data, and G is an intermediate data created for set operations in the DS fusion process.

**Comment by xunchang88** [comment]
Thanks very much for your reply.
I have another question: If M is a 5*1000 matrix, that is, there are 5 sensors, each sensor contains 1000 sampling point data, then how should G change? Will it become a 1001*1000 matrix? The first 1000 rows of this matrix are unit matrices, and the elements in the last row are all 1.

**Comment by JethroJames** [comment]
Your understanding is spot on; there are no issues with what you've described.

**Comment by xunchang88** [comment]
In this way, the "cluster" will be 5 or 1000?

**Comment by JethroJames** [comment]
1000
